/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STM32F103x6.h"
#include "STM32F103x6_GPIO_Driver.h"
#include "STM32F103x6_EXTI_Driver.h"
#include "STM32F103x6_USART_Driver.h"
#include "STM32F103x6_RCC_Driver.h"
#include "STM32F103x6_SPI_Driver.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define SPI_MASTER_MCU
//#define SPI_SLAVE_MCU

uint16_t Ch1;

void myUSART1Handler()
{

#ifdef SPI_MASTER_MCU
	MCAL_USART_ReceiveData(USART1, &Ch1, USART_Interrupt);
	MCAL_USART_SendData(USART1, &Ch1, USART_Polling);

	MCAL_GPIO_WritePin(GPIOA, GPIO_PinNumber_4, GPIO_PinValue_LOW);
	MCAL_SPI_SendReceiveData(SPI1, &Ch1, SPI_PollingENABLE, &Ch1, SPI_PollingENABLE);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PinNumber_4, GPIO_PinValue_HIGH);
#endif

}

void mySPI1Handler(SPI_InterruptSource_t InterruptSource)
{

#ifdef SPI_SLAVE_MCU
	if (InterruptSource.RXNE)
	{
		Ch1=0xF;
		MCAL_SPI_SendReceiveData(SPI1, &Ch1, SPI_PollingENABLE, &Ch1, SPI_Interrupt);
		MCAL_USART_SendData(USART1, &Ch1, USART_Polling);
	}
#endif

}

void clock_init()
{
	RCC_GPIOA_CLK_EN(); //Enable PORTA Clock
	RCC_GPIOB_CLK_EN(); //Enable PORTB Clock
	RCC_AFIO_CLK_EN();	//Enable AFIO Clock
}

void USART_init()
{
	USART_Config_t myusartConfig;

	myusartConfig.USART_TxRxMode = USART_TxRxMode_TXandRX;
	myusartConfig.USART_WordLength = USART_WordLength_8BITS;
	myusartConfig.USART_Parity = USART_Parity_NONE;
	myusartConfig.USART_StopBits = USART_StopBits_1BIT;
	myusartConfig.USART_BaudRate = USART_BaudRate_19200bps;
	myusartConfig.USART_FlowControl = USART_FlowControl_NONE;
	myusartConfig.USART_Interrupt_EN = USART_Interrupt_EN_RXNE;
	myusartConfig.USART_ptr_irqCallbackFUN = &myUSART1Handler;
	MCAL_USART_Init(USART1, &myusartConfig);
}

void SPI_init()
{
	SPI_Config_t mySPIConfig;

	mySPIConfig.SPI_CommunicationMode = SPI_CommunicationMode_FULL_DUPLEX_UNIDIRECTION_TXandRX;
	mySPIConfig.SPI_DataLength = SPI_DataLength_8BITS;
	mySPIConfig.SPI_FrameFormat = SPI_FrameFormat_MSB_FIRST;
	mySPIConfig.SPI_ClockPolarity = SPI_ClockPolarity_HIGH_IDLE;
	mySPIConfig.SPI_ClockPhase = SPI_ClockPhase_2ND_EDGE_CAPTURE;
	mySPIConfig.SPI_ClockPreScaler = SPI_ClockPreScaler_8;

#ifdef SPI_MASTER_MCU
	mySPIConfig.SPI_DeviceMode = SPI_DeviceMode_MASTER;
	mySPIConfig.SPI_NSS = SPI_NSS_SW_HIGH;
	mySPIConfig.SPI_Interrupt_EN = SPI_Interrupt_EN_NONE;
	mySPIConfig.SPI_ptr_irqCallbackFUN = NULL;
#endif

#ifdef SPI_SLAVE_MCU
	mySPIConfig.SPI_DeviceMode = SPI_DeviceMode_SLAVE;
	mySPIConfig.SPI_NSS = SPI_NSS_HW_SLAVE_INPUT;
	mySPIConfig.SPI_Interrupt_EN = SPI_Interrupt_EN_RXNE;
	mySPIConfig.SPI_ptr_irqCallbackFUN = &mySPI1Handler;
#endif

	MCAL_SPI_Init(SPI1, &mySPIConfig, SingleMaster_SingleSlave);
}

void GPIO_init()
{

#ifdef SPI_MASTER_MCU
	GPIO_PinConfig_t mypinConfig;

	//PA.4 General purpose output push-pull, max speed 2 MHz.
	//Used as slave select pin for SPI
	mypinConfig.GPIO_PinNumber = GPIO_PinNumber_4;
	mypinConfig.GPIO_PinMode = GPIO_PinMode_Output_PUSHPULL;
	mypinConfig.GPIO_PinSpeed = GPIO_PinSpeed_2MHz;
	MCAL_GPIO_InitPin(GPIOA, &mypinConfig);

	//Slave select is HIGH idle.
	MCAL_GPIO_WritePin(GPIOA, GPIO_PinNumber_4, GPIO_PinValue_HIGH);
#endif

}

int main(void)
{
	clock_init();
	USART_init();
	SPI_init();
	GPIO_init();

	while(1)
	{
	}
}
