/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STM32F103x6.h"
#include "STM32F103x6_GPIO_Driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void clock_init()
{
	RCC_GPIOA_CLK_EN(); //Enable PORTA Clock
	RCC_GPIOB_CLK_EN(); //Enable PORTB Clock
}
void GPIOA_init()
{
	GPIO_PinConfig_t mypinConfig;

	//PA.1 Input with pull-up.
	mypinConfig.GPIO_PinNumber = GPIO_PinNumber_1;
	mypinConfig.GPIO_PinMode = GPIO_PinMode_Input_FLOATING;
	MCAL_GPIO_InitPin(GPIOA, &mypinConfig);

	//PA.13 Input with pull-down.
	mypinConfig.GPIO_PinNumber = GPIO_PinNumber_13;
	mypinConfig.GPIO_PinMode = GPIO_PinMode_Input_FLOATING;
	MCAL_GPIO_InitPin(GPIOA, &mypinConfig);

	MCAL_GPIO_LockPin(GPIOA, GPIO_PinNumber_1 | GPIO_PinNumber_13);

	//PB.1 General purpose output push-pull, max speed 2 MHz.
	mypinConfig.GPIO_PinNumber = GPIO_PinNumber_1;
	mypinConfig.GPIO_PinMode = GPIO_PinMode_Output_PUSHPULL;
	mypinConfig.GPIO_PinSpeed = GPIO_PinSpeed_2MHz;
	MCAL_GPIO_InitPin(GPIOB, &mypinConfig);

	//PB.13 General purpose output push-pull, max speed 2 MHz.
	mypinConfig.GPIO_PinNumber = GPIO_PinNumber_13;
	mypinConfig.GPIO_PinMode = GPIO_PinMode_Output_PUSHPULL;
	mypinConfig.GPIO_PinSpeed = GPIO_PinSpeed_2MHz;
	MCAL_GPIO_InitPin(GPIOB, &mypinConfig);

	MCAL_GPIO_LockPin(GPIOB, GPIO_PinNumber_1 | GPIO_PinNumber_13);
}

void mydelay(uint8_t time)
{
	uint8_t i , j;
	for (i = 0; i < time; i++)
	{
		for (j = 0; j < 255; j++)
		{
		}
	}
}

int main(void)
{
	clock_init();
	GPIOA_init();

	while(1)
	{
		if (MCAL_GPIO_ReadPin(GPIOA, GPIO_PinNumber_13) == 1) //PA.13: Floating input with external PDR
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PinNumber_13); //Toggle LED connected to PB.13
			//Multiple Pressing
		}

		if (MCAL_GPIO_ReadPin(GPIOA, GPIO_PinNumber_1) == 0) //PA.1: Floating input with external PUR
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PinNumber_1); //Toggle LED connected to PB.1
			//Single Pressing
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PinNumber_1) == 0);
		}

		mydelay(1);
	}
}
