/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STM32F103x6.h"
#include "STM32F103x6_GPIO_Driver.h"
#include "STM32F103x6_EXTI_Driver.h"
#include "STM32F103x6_RCC_Driver.h"
#include "STM32F103x6_USART_Driver.h"
#include "STM32F103x6_SPI_Driver.h"
#include "STM32F103x6_I2C_Driver.h"

#include "EEPROM_SlaveI2C.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void clock_init()
{
	RCC_GPIOA_CLK_EN(); //Enable PORTA Clock
	RCC_GPIOB_CLK_EN(); //Enable PORTB Clock
	RCC_AFIO_CLK_EN();	//Enable AFIO Clock
}
void EEPROM_init()
{
	HAL_EEPROM_Init();
}

int main(void)
{
	clock_init();
	EEPROM_init();

	//Test case 1
	uint8_t Arr1[7] = {0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7};
	uint8_t Arr2[7] = {0};
	HAL_EEPROM_Write(0XAF, Arr1, sizeof(Arr1)/sizeof(Arr1[1]));
	HAL_EEPROM_Read(0XAF, Arr2, sizeof(Arr1)/sizeof(Arr1[1]));

	//Corner test cases
	Arr1[0] = 0xA;
	Arr1[1] = 0xB;
	Arr1[2] = 0xC;
	Arr1[3] = 0xD;

	//Number of bytes in Tx and Rx is 2 bytes. -----> Passed
	HAL_EEPROM_Write(0XFFF, Arr1, 2);
	HAL_EEPROM_Read(0XFFF, Arr2, 2);

	//Number of bytes in Tx and Rx is 0 bytes. -----> Passed
	HAL_EEPROM_Write(0XF, Arr1, 0);
	HAL_EEPROM_Read(0XF, Arr2, 0);

	//Number of bytes in Tx and Rx is 1 bytes. -----> Passed
	HAL_EEPROM_Write(0X0FF, Arr1, 1);
	HAL_EEPROM_Read(0X0FF, Arr2, 1);

	while(1)
	{

	}
}
