/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "Clock_Registers.h"
#include "GPIOx_Registers.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void clock_init()
{
	volatile RCC_APB2ENR_t* const RCC_APB2ENR = (RCC_APB2ENR_t*)(RCC_BASE+RCC_APB2ENR_OFFSET);

	RCC_APB2ENR->IOPAEN = 0b1; //Enable PORTA Clock
	RCC_APB2ENR->IOPBEN = 0b1; //Enable PORTB Clock
}
void GPIOA_init()
{
	//PORTA registers
	volatile GPIOx_CRL_t* const GPIOA_CRL = (GPIOx_CRL_t*)(PORTA_BASE+GPIOx_CRL_OFFSET);
	volatile GPIOx_CRH_t* const GPIOA_CRH = (GPIOx_CRH_t*)(PORTA_BASE+GPIOx_CRH_OFFSET);

	//PORTB registers
	volatile GPIOx_CRL_t* const GPIOB_CRL = (GPIOx_CRL_t*)(PORTB_BASE+GPIOx_CRL_OFFSET);
	volatile GPIOx_CRH_t* const GPIOB_CRH = (GPIOx_CRH_t*)(PORTB_BASE+GPIOx_CRH_OFFSET);

	//Port A mode bits
	GPIOA_CRL->MODE1 = 0b00; // 00: Input mode (reset state)
	GPIOA_CRH->MODE13 = 0b00; // 00: Input mode (reset state)
	//Port A configuration bits
	GPIOA_CRL->CNF1 = 0b01; // 01: Floating input (reset state)
	GPIOA_CRH->CNF13 = 0b01; // 00: Floating input (reset state)

	//Port B mode bits
	GPIOB_CRL->MODE1 = 0b10; // 10: Output mode, max speed 2 MHz.
	GPIOB_CRH->MODE13 = 0b10; // 10: Output mode, max speed 2 MHz.
	//Port B configuration bits
	GPIOB_CRL->CNF1 = 0b00; // 00: General purpose output push-pull
	GPIOB_CRH->CNF13 = 0b00; // 00: General purpose output push-pull
}

void mydelay(uint8_t time)
{
	uint8_t i , j;
	for (i = 0; i < time; i++)
	{
		for (j = 0; j < 255; j++)
		{
		}
	}
}

int main(void)
{
	clock_init();
	GPIOA_init();

	//PORTA registers (INPUT)
	volatile GPIOx_IDR_t* const GPIOA_IDR = (GPIOx_IDR_t*)(PORTA_BASE+GPIOx_IDR_OFFSET);

	//PORTB registers (OUTPUT)
	volatile GPIOx_ODR_t* const GPIOB_ODR = (GPIOx_ODR_t*)(PORTB_BASE+GPIOx_ODR_OFFSET);

	while(1)
	{
		if (GPIOA_IDR->IDR13 == 1) //PA.13: Floating input with external PDR
		{
			GPIOB_ODR->ODR13 ^= 1; //Toggle LED connected to PA.13
			//Multiple Pressing
		}

		if (GPIOA_IDR->IDR1 == 0) //PA.1: Floating input with external PUR
		{
			GPIOB_ODR->ODR1 ^= 1; //Toggle LED connected to PA.1
			//Single Pressing
			while(GPIOA_IDR->IDR1 == 0);
		}

		mydelay(1);
	}
}
