/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STM32F103x6.h"
#include "STM32F103x6_GPIO_Driver.h"
#include "STM32F103x6_EXTI_Driver.h"
#include "STM32F103x6_USART_Driver.h"
#include "STM32F103x6_RCC_Driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint16_t Ch1;
uint16_t Ch2;

void myUSART2Handler()
{
	MCAL_USART_ReceiveData(USART2, &Ch2, Interrupt);
	MCAL_USART_SendData(USART2, &Ch2, Polling);
}

void clock_init()
{
	RCC_GPIOA_CLK_EN(); //Enable PORTA Clock
	RCC_GPIOB_CLK_EN(); //Enable PORTB Clock
	RCC_AFIO_CLK_EN();	//Enable AFIO Clock
}

void USART_init()
{
	USART_Config_t myusartConfig;
	myusartConfig.USART_TxRxMode = USART_TxRxMode_TXandRX;
	myusartConfig.USART_WordLength = USART_WordLength_9BITS;
	myusartConfig.USART_Parity = USART_Parity_EVEN;
	myusartConfig.USART_StopBits = USART_StopBits_1BIT;
	myusartConfig.USART_BaudRate = USART_BaudRate_115200bps;
	myusartConfig.USART_FlowControl = USART_FlowControl_NONE;
	myusartConfig.USART_Interrupt_EN = USART_Interrupt_EN_NONE;
	myusartConfig.USART_ptr_irqCallbackFUN = NULL;
	MCAL_USART_Init(USART1, &myusartConfig);

	myusartConfig.USART_TxRxMode = USART_TxRxMode_TXandRX;
	myusartConfig.USART_WordLength = USART_WordLength_8BITS;
	myusartConfig.USART_Parity = USART_Parity_NONE;
	myusartConfig.USART_StopBits = USART_StopBits_1BIT;
	myusartConfig.USART_BaudRate = USART_BaudRate_19200bps;
	myusartConfig.USART_FlowControl = USART_FlowControl_NONE;
	myusartConfig.USART_Interrupt_EN = USART_Interrupt_EN_RXNE;
	myusartConfig.USART_ptr_irqCallbackFUN = &myUSART2Handler;
	MCAL_USART_Init(USART2, &myusartConfig);
}

int main(void)
{
	clock_init();
	USART_init();

	while(1)
	{
		MCAL_USART_ReceiveData(USART1, &Ch1, Polling);
		MCAL_USART_SendData(USART1, &Ch1, Polling);
	}
}
